name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: actions/upload-artifact@v4
      with:
        name: buildArtifact
        path: target/*.jar
        
  Deployment:

    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        deployHosts: ['34.227.176.180', '23.23.33.230']
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: buildArtifact
        path: .
    - name: Deploy Artifacts
      run: ls -laRt
    - name: copy file to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ matrix.deployHosts }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        port: 22
        source: '*.jar'
        target: /tmp/
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ matrix.deployHosts }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        port: 22
        script: |
           sudo cp /tmp/*.jar /opt/
           sudo ls -lart /opt
